name: Health check

on: [ "push" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Build
      run: cargo build --all-features --verbose --workspace --tests --examples
    - name: Clippy
      run: cargo clippy --all-features --workspace --tests --examples
    - name: Run tests
      run: cargo test --verbose
    - name: Format
      run: cargo fmt --check --all
